# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tourna.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tournament_ui(object):
    def setupUi(self, tournament_ui):
        tournament_ui.setObjectName("tournament_ui")
        tournament_ui.resize(685, 688)
        tournament_ui.setMinimumSize(QtCore.QSize(330, 194))
        tournament_ui.setWizardStyle(QtWidgets.QWizard.ClassicStyle)
        self.FileSelectionPg = QtWidgets.QWizardPage()
        self.FileSelectionPg.setObjectName("FileSelectionPg")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.FileSelectionPg)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.FileSelectionPg)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(430, 437))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("wtc.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_1_1 = QtWidgets.QLabel(self.FileSelectionPg)
        self.label_1_1.setMinimumSize(QtCore.QSize(90, 0))
        self.label_1_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_1_1.setObjectName("label_1_1")
        self.horizontalLayout_4.addWidget(self.label_1_1)
        self.txt_settingsfile_in = QtWidgets.QLineEdit(self.FileSelectionPg)
        self.txt_settingsfile_in.setDragEnabled(True)
        self.txt_settingsfile_in.setClearButtonEnabled(False)
        self.txt_settingsfile_in.setObjectName("txt_settingsfile_in")
        self.horizontalLayout_4.addWidget(self.txt_settingsfile_in)
        self.btn_explore_1_1 = QtWidgets.QPushButton(self.FileSelectionPg)
        self.btn_explore_1_1.setObjectName("btn_explore_1_1")
        self.horizontalLayout_4.addWidget(self.btn_explore_1_1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_1_2 = QtWidgets.QLabel(self.FileSelectionPg)
        self.label_1_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_1_2.setObjectName("label_1_2")
        self.horizontalLayout_6.addWidget(self.label_1_2)
        self.txt_settingsfile_out = QtWidgets.QLineEdit(self.FileSelectionPg)
        self.txt_settingsfile_out.setObjectName("txt_settingsfile_out")
        self.horizontalLayout_6.addWidget(self.txt_settingsfile_out)
        self.btn_explore_1_2 = QtWidgets.QPushButton(self.FileSelectionPg)
        self.btn_explore_1_2.setObjectName("btn_explore_1_2")
        self.horizontalLayout_6.addWidget(self.btn_explore_1_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.btn_load = QtWidgets.QPushButton(self.FileSelectionPg)
        self.btn_load.setObjectName("btn_load")
        self.horizontalLayout_3.addWidget(self.btn_load)
        self.chk_music = QtWidgets.QCheckBox(self.FileSelectionPg)
        self.chk_music.setEnabled(False)
        self.chk_music.setText("")
        self.chk_music.setObjectName("chk_music")
        self.horizontalLayout_3.addWidget(self.chk_music)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        tournament_ui.addPage(self.FileSelectionPg)
        self.PlayerSelectionPg = QtWidgets.QWizardPage()
        self.PlayerSelectionPg.setObjectName("PlayerSelectionPg")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.PlayerSelectionPg)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_1_3 = QtWidgets.QLabel(self.PlayerSelectionPg)
        self.label_1_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_1_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_1_3.setObjectName("label_1_3")
        self.horizontalLayout_5.addWidget(self.label_1_3)
        self.txt_dir_players = QtWidgets.QLineEdit(self.PlayerSelectionPg)
        self.txt_dir_players.setDragEnabled(True)
        self.txt_dir_players.setClearButtonEnabled(False)
        self.txt_dir_players.setObjectName("txt_dir_players")
        self.horizontalLayout_5.addWidget(self.txt_dir_players)
        self.btn_explore_2_1 = QtWidgets.QPushButton(self.PlayerSelectionPg)
        self.btn_explore_2_1.setObjectName("btn_explore_2_1")
        self.horizontalLayout_5.addWidget(self.btn_explore_2_1)
        self.btn_player_update = QtWidgets.QPushButton(self.PlayerSelectionPg)
        self.btn_player_update.setObjectName("btn_player_update")
        self.horizontalLayout_5.addWidget(self.btn_player_update)
        self.verticalLayout_20.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(self.PlayerSelectionPg)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_20.addWidget(self.line)
        self.label_25 = QtWidgets.QLabel(self.PlayerSelectionPg)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_20.addWidget(self.label_25)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.PlayerSelectionPg)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.lst_players_deselect = QtWidgets.QListWidget(self.PlayerSelectionPg)
        self.lst_players_deselect.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.lst_players_deselect.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lst_players_deselect.setObjectName("lst_players_deselect")
        self.verticalLayout_6.addWidget(self.lst_players_deselect)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.btn_players_select = QtWidgets.QPushButton(self.PlayerSelectionPg)
        self.btn_players_select.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_players_select.setObjectName("btn_players_select")
        self.verticalLayout_4.addWidget(self.btn_players_select, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem3)
        self.btn_players_deselect = QtWidgets.QPushButton(self.PlayerSelectionPg)
        self.btn_players_deselect.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_players_deselect.setObjectName("btn_players_deselect")
        self.verticalLayout_4.addWidget(self.btn_players_deselect, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_3 = QtWidgets.QLabel(self.PlayerSelectionPg)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_19.addWidget(self.label_3)
        self.lst_players_select = QtWidgets.QListWidget(self.PlayerSelectionPg)
        self.lst_players_select.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.lst_players_select.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lst_players_select.setObjectName("lst_players_select")
        self.verticalLayout_19.addWidget(self.lst_players_select)
        self.horizontalLayout_7.addLayout(self.verticalLayout_19)
        self.verticalLayout_20.addLayout(self.horizontalLayout_7)
        tournament_ui.addPage(self.PlayerSelectionPg)
        self.TypeSelectionPg = QtWidgets.QWizardPage()
        self.TypeSelectionPg.setObjectName("TypeSelectionPg")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.TypeSelectionPg)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.TypeSelectionPg)
        self.scrollArea_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 624, 678))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("round.PNG"))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_17.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("single elim.jpg"))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_17.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_17)
        spacerItem5 = QtWidgets.QSpacerItem(102, 147, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rbtn_robin = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbtn_robin.setMinimumSize(QtCore.QSize(110, 50))
        self.rbtn_robin.setIconSize(QtCore.QSize(25, 25))
        self.rbtn_robin.setChecked(True)
        self.rbtn_robin.setObjectName("rbtn_robin")
        self.btngrp_tournament_type = QtWidgets.QButtonGroup(tournament_ui)
        self.btngrp_tournament_type.setObjectName("btngrp_tournament_type")
        self.btngrp_tournament_type.addButton(self.rbtn_robin)
        self.verticalLayout_2.addWidget(self.rbtn_robin)
        self.rbtn_single = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbtn_single.setMinimumSize(QtCore.QSize(120, 50))
        self.rbtn_single.setChecked(False)
        self.rbtn_single.setObjectName("rbtn_single")
        self.btngrp_tournament_type.addButton(self.rbtn_single)
        self.verticalLayout_2.addWidget(self.rbtn_single)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_11.addWidget(self.line_3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("swiss.PNG"))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_18.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("double elim.gif"))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_18.addWidget(self.label_10)
        self.horizontalLayout_12.addLayout(self.verticalLayout_18)
        spacerItem7 = QtWidgets.QSpacerItem(102, 147, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.rbtn_swiss = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbtn_swiss.setEnabled(False)
        self.rbtn_swiss.setMinimumSize(QtCore.QSize(110, 0))
        self.rbtn_swiss.setIconSize(QtCore.QSize(25, 25))
        self.rbtn_swiss.setChecked(False)
        self.rbtn_swiss.setObjectName("rbtn_swiss")
        self.btngrp_tournament_type.addButton(self.rbtn_swiss)
        self.verticalLayout_14.addWidget(self.rbtn_swiss)
        self.rbtn_multi = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.rbtn_multi.setEnabled(False)
        self.rbtn_multi.setMinimumSize(QtCore.QSize(120, 0))
        self.rbtn_multi.setObjectName("rbtn_multi")
        self.btngrp_tournament_type.addButton(self.rbtn_multi)
        self.verticalLayout_14.addWidget(self.rbtn_multi)
        self.horizontalLayout_12.addLayout(self.verticalLayout_14)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_12.addWidget(self.scrollArea_5)
        tournament_ui.addPage(self.TypeSelectionPg)
        self.TournamentSettingsPg = QtWidgets.QWizardPage()
        self.TournamentSettingsPg.setObjectName("TournamentSettingsPg")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.TournamentSettingsPg)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.TournamentSettingsPg)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.roundrobin_elim_tab = QtWidgets.QWidget()
        self.roundrobin_elim_tab.setObjectName("roundrobin_elim_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.roundrobin_elim_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.chk_robin_groups = QtWidgets.QCheckBox(self.roundrobin_elim_tab)
        self.chk_robin_groups.setObjectName("chk_robin_groups")
        self.horizontalLayout_10.addWidget(self.chk_robin_groups)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.label_robbin_groups = QtWidgets.QLabel(self.roundrobin_elim_tab)
        self.label_robbin_groups.setEnabled(False)
        self.label_robbin_groups.setObjectName("label_robbin_groups")
        self.horizontalLayout_10.addWidget(self.label_robbin_groups)
        self.spn_robin_groups = QtWidgets.QSpinBox(self.roundrobin_elim_tab)
        self.spn_robin_groups.setEnabled(False)
        self.spn_robin_groups.setMinimum(1)
        self.spn_robin_groups.setObjectName("spn_robin_groups")
        self.horizontalLayout_10.addWidget(self.spn_robin_groups)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        spacerItem9 = QtWidgets.QSpacerItem(20, 490, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.tabWidget.addTab(self.roundrobin_elim_tab, "")
        self.single_elim_tab = QtWidgets.QWidget()
        self.single_elim_tab.setObjectName("single_elim_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.single_elim_tab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.chk_single_third = QtWidgets.QCheckBox(self.single_elim_tab)
        self.chk_single_third.setEnabled(False)
        self.chk_single_third.setObjectName("chk_single_third")
        self.verticalLayout_8.addWidget(self.chk_single_third)
        spacerItem10 = QtWidgets.QSpacerItem(20, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.tabWidget.addTab(self.single_elim_tab, "")
        self.multi_elim_tab = QtWidgets.QWidget()
        self.multi_elim_tab.setObjectName("multi_elim_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.multi_elim_tab)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.multi_elim_tab)
        self.label_13.setEnabled(False)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        self.line_6 = QtWidgets.QFrame(self.multi_elim_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_15.addWidget(self.line_6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(self.multi_elim_tab)
        self.label_14.setEnabled(True)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.spn_multi_amount = QtWidgets.QSpinBox(self.multi_elim_tab)
        self.spn_multi_amount.setEnabled(True)
        self.spn_multi_amount.setMinimum(1)
        self.spn_multi_amount.setObjectName("spn_multi_amount")
        self.horizontalLayout_16.addWidget(self.spn_multi_amount)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        spacerItem11 = QtWidgets.QSpacerItem(20, 490, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem11)
        self.tabWidget.addTab(self.multi_elim_tab, "")
        self.swiss_tab = QtWidgets.QWidget()
        self.swiss_tab.setObjectName("swiss_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.swiss_tab)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.swiss_tab)
        self.label_12.setEnabled(False)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.line_5 = QtWidgets.QFrame(self.swiss_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_14.addWidget(self.line_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.chk_swiss_pnt = QtWidgets.QCheckBox(self.swiss_tab)
        self.chk_swiss_pnt.setObjectName("chk_swiss_pnt")
        self.horizontalLayout_20.addWidget(self.chk_swiss_pnt)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem12)
        self.spn_swiss_pnt = QtWidgets.QSpinBox(self.swiss_tab)
        self.spn_swiss_pnt.setObjectName("spn_swiss_pnt")
        self.horizontalLayout_20.addWidget(self.spn_swiss_pnt)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.chk_swiss_replay = QtWidgets.QCheckBox(self.swiss_tab)
        self.chk_swiss_replay.setObjectName("chk_swiss_replay")
        self.verticalLayout_9.addWidget(self.chk_swiss_replay)
        spacerItem13 = QtWidgets.QSpacerItem(20, 467, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem13)
        self.tabWidget.addTab(self.swiss_tab, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        tournament_ui.addPage(self.TournamentSettingsPg)
        self.GeneralSettingPg = QtWidgets.QWizardPage()
        self.GeneralSettingPg.setObjectName("GeneralSettingPg")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.GeneralSettingPg)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_20 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_16.addWidget(self.label_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem14)
        self.label_19 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_19.setMinimumSize(QtCore.QSize(50, 0))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.spn_set_bestof = QtWidgets.QSpinBox(self.GeneralSettingPg)
        self.spn_set_bestof.setMinimum(1)
        self.spn_set_bestof.setSingleStep(2)
        self.spn_set_bestof.setProperty("value", 1)
        self.spn_set_bestof.setObjectName("spn_set_bestof")
        self.horizontalLayout_19.addWidget(self.spn_set_bestof)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem15)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem16)
        self.horizontalLayout_36.addLayout(self.verticalLayout_16)
        self.line_13 = QtWidgets.QFrame(self.GeneralSettingPg)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_36.addWidget(self.line_13)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_22 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_24.addWidget(self.label_22)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem17)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_23 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_23.setMinimumSize(QtCore.QSize(27, 0))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_25.addWidget(self.label_23)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem18)
        self.spn_set_winpnt = QtWidgets.QSpinBox(self.GeneralSettingPg)
        self.spn_set_winpnt.setMinimum(1)
        self.spn_set_winpnt.setSingleStep(1)
        self.spn_set_winpnt.setProperty("value", 2)
        self.spn_set_winpnt.setObjectName("spn_set_winpnt")
        self.horizontalLayout_25.addWidget(self.spn_set_winpnt)
        self.verticalLayout_22.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_24 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_24.setEnabled(False)
        self.label_24.setMinimumSize(QtCore.QSize(27, 0))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_24.addWidget(self.label_24)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem19)
        self.spn_set_drawpnt = QtWidgets.QSpinBox(self.GeneralSettingPg)
        self.spn_set_drawpnt.setEnabled(False)
        self.spn_set_drawpnt.setMinimum(0)
        self.spn_set_drawpnt.setSingleStep(1)
        self.spn_set_drawpnt.setProperty("value", 1)
        self.spn_set_drawpnt.setObjectName("spn_set_drawpnt")
        self.horizontalLayout_24.addWidget(self.spn_set_drawpnt)
        self.verticalLayout_22.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_26 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_26.setMinimumSize(QtCore.QSize(27, 0))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_23.addWidget(self.label_26)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem20)
        self.spn_set_losspnt = QtWidgets.QSpinBox(self.GeneralSettingPg)
        self.spn_set_losspnt.setMinimum(0)
        self.spn_set_losspnt.setSingleStep(1)
        self.spn_set_losspnt.setProperty("value", 0)
        self.spn_set_losspnt.setObjectName("spn_set_losspnt")
        self.horizontalLayout_23.addWidget(self.spn_set_losspnt)
        self.verticalLayout_22.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_27.addLayout(self.verticalLayout_22)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem21)
        self.verticalLayout_24.addLayout(self.horizontalLayout_27)
        spacerItem22 = QtWidgets.QSpacerItem(20, 330, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem22)
        self.horizontalLayout_36.addLayout(self.verticalLayout_24)
        self.verticalLayout_29.addLayout(self.horizontalLayout_36)
        self.line_11 = QtWidgets.QFrame(self.GeneralSettingPg)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_29.addWidget(self.line_11)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.rbtn_set_noseed = QtWidgets.QRadioButton(self.GeneralSettingPg)
        self.rbtn_set_noseed.setChecked(True)
        self.rbtn_set_noseed.setObjectName("rbtn_set_noseed")
        self.btngrp_seed_type = QtWidgets.QButtonGroup(tournament_ui)
        self.btngrp_seed_type.setObjectName("btngrp_seed_type")
        self.btngrp_seed_type.addButton(self.rbtn_set_noseed)
        self.verticalLayout_11.addWidget(self.rbtn_set_noseed)
        self.rbtn_set_rdmseed = QtWidgets.QRadioButton(self.GeneralSettingPg)
        self.rbtn_set_rdmseed.setEnabled(True)
        self.rbtn_set_rdmseed.setCheckable(True)
        self.rbtn_set_rdmseed.setChecked(False)
        self.rbtn_set_rdmseed.setObjectName("rbtn_set_rdmseed")
        self.btngrp_seed_type.addButton(self.rbtn_set_rdmseed)
        self.verticalLayout_11.addWidget(self.rbtn_set_rdmseed)
        self.rbtn_set_seeded = QtWidgets.QRadioButton(self.GeneralSettingPg)
        self.rbtn_set_seeded.setEnabled(False)
        self.rbtn_set_seeded.setObjectName("rbtn_set_seeded")
        self.btngrp_seed_type.addButton(self.rbtn_set_seeded)
        self.verticalLayout_11.addWidget(self.rbtn_set_seeded)
        self.horizontalLayout_17.addLayout(self.verticalLayout_11)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_17)
        self.line_14 = QtWidgets.QFrame(self.GeneralSettingPg)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.horizontalLayout_26.addWidget(self.line_14)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.radioButton = QtWidgets.QRadioButton(self.GeneralSettingPg)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.btngrp_score_show = QtWidgets.QButtonGroup(tournament_ui)
        self.btngrp_score_show.setObjectName("btngrp_score_show")
        self.btngrp_score_show.addButton(self.radioButton)
        self.verticalLayout_23.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.GeneralSettingPg)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.btngrp_score_show.addButton(self.radioButton_2)
        self.verticalLayout_23.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.GeneralSettingPg)
        self.radioButton_3.setObjectName("radioButton_3")
        self.btngrp_score_show.addButton(self.radioButton_3)
        self.verticalLayout_23.addWidget(self.radioButton_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_23)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_2)
        self.verticalLayout_29.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_15.setEnabled(False)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.line_7 = QtWidgets.QFrame(self.GeneralSettingPg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_8.addWidget(self.line_7)
        self.verticalLayout_29.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.chk_set_watch = QtWidgets.QCheckBox(self.GeneralSettingPg)
        self.chk_set_watch.setEnabled(False)
        self.chk_set_watch.setObjectName("chk_set_watch")
        self.verticalLayout_21.addWidget(self.chk_set_watch)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_21.setEnabled(False)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem23)
        self.spn_set_pause = QtWidgets.QDoubleSpinBox(self.GeneralSettingPg)
        self.spn_set_pause.setEnabled(False)
        self.spn_set_pause.setObjectName("spn_set_pause")
        self.horizontalLayout_22.addWidget(self.spn_set_pause)
        self.verticalLayout_21.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_37.addLayout(self.verticalLayout_21)
        self.line_12 = QtWidgets.QFrame(self.GeneralSettingPg)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_37.addWidget(self.line_12)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_17 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_17.setEnabled(False)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_15.addWidget(self.label_17)
        self.chk_set_elo = QtWidgets.QCheckBox(self.GeneralSettingPg)
        self.chk_set_elo.setEnabled(False)
        self.chk_set_elo.setObjectName("chk_set_elo")
        self.verticalLayout_15.addWidget(self.chk_set_elo)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_1_4 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_1_4.setEnabled(False)
        self.label_1_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_1_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_1_4.setObjectName("label_1_4")
        self.horizontalLayout_21.addWidget(self.label_1_4)
        self.txt_elofile = QtWidgets.QLineEdit(self.GeneralSettingPg)
        self.txt_elofile.setEnabled(False)
        self.txt_elofile.setDragEnabled(True)
        self.txt_elofile.setClearButtonEnabled(False)
        self.txt_elofile.setObjectName("txt_elofile")
        self.horizontalLayout_21.addWidget(self.txt_elofile)
        self.btn_explore_5_1 = QtWidgets.QPushButton(self.GeneralSettingPg)
        self.btn_explore_5_1.setEnabled(False)
        self.btn_explore_5_1.setObjectName("btn_explore_5_1")
        self.horizontalLayout_21.addWidget(self.btn_explore_5_1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.GeneralSettingPg)
        self.label_18.setEnabled(False)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.spn_set_kval = QtWidgets.QDoubleSpinBox(self.GeneralSettingPg)
        self.spn_set_kval.setEnabled(False)
        self.spn_set_kval.setDecimals(1)
        self.spn_set_kval.setProperty("value", 32.0)
        self.spn_set_kval.setObjectName("spn_set_kval")
        self.horizontalLayout_18.addWidget(self.spn_set_kval)
        self.verticalLayout_15.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_37.addLayout(self.verticalLayout_15)
        self.verticalLayout_29.addLayout(self.horizontalLayout_37)
        tournament_ui.addPage(self.GeneralSettingPg)
        self.VMSettingsPg = QtWidgets.QWizardPage()
        self.VMSettingsPg.setObjectName("VMSettingsPg")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.VMSettingsPg)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_33 = QtWidgets.QLabel(self.VMSettingsPg)
        self.label_33.setEnabled(True)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_28.addWidget(self.label_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_32 = QtWidgets.QLabel(self.VMSettingsPg)
        self.label_32.setEnabled(False)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_34.addWidget(self.label_32)
        self.line_9 = QtWidgets.QFrame(self.VMSettingsPg)
        self.line_9.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_9.sizePolicy().hasHeightForWidth())
        self.line_9.setSizePolicy(sizePolicy)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_34.addWidget(self.line_9)
        self.verticalLayout_28.addLayout(self.horizontalLayout_34)
        self.btn_vminfo = QtWidgets.QPushButton(self.VMSettingsPg)
        self.btn_vminfo.setEnabled(False)
        self.btn_vminfo.setObjectName("btn_vminfo")
        self.verticalLayout_28.addWidget(self.btn_vminfo)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem24)
        self.rbtn_vm = QtWidgets.QRadioButton(self.VMSettingsPg)
        self.rbtn_vm.setEnabled(False)
        self.rbtn_vm.setChecked(True)
        self.rbtn_vm.setObjectName("rbtn_vm")
        self.horizontalLayout_32.addWidget(self.rbtn_vm)
        spacerItem25 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem25)
        self.rbtn_script = QtWidgets.QRadioButton(self.VMSettingsPg)
        self.rbtn_script.setEnabled(False)
        self.rbtn_script.setObjectName("rbtn_script")
        self.horizontalLayout_32.addWidget(self.rbtn_script)
        spacerItem26 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem26)
        self.verticalLayout_28.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_1_6 = QtWidgets.QLabel(self.VMSettingsPg)
        self.label_1_6.setEnabled(False)
        self.label_1_6.setMinimumSize(QtCore.QSize(80, 0))
        self.label_1_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_1_6.setObjectName("label_1_6")
        self.horizontalLayout_30.addWidget(self.label_1_6)
        self.txt_vmloc = QtWidgets.QLineEdit(self.VMSettingsPg)
        self.txt_vmloc.setEnabled(False)
        self.txt_vmloc.setDragEnabled(True)
        self.txt_vmloc.setClearButtonEnabled(False)
        self.txt_vmloc.setObjectName("txt_vmloc")
        self.horizontalLayout_30.addWidget(self.txt_vmloc)
        self.btn_explore_6_1 = QtWidgets.QPushButton(self.VMSettingsPg)
        self.btn_explore_6_1.setEnabled(False)
        self.btn_explore_6_1.setObjectName("btn_explore_6_1")
        self.horizontalLayout_30.addWidget(self.btn_explore_6_1)
        self.verticalLayout_27.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_30 = QtWidgets.QLabel(self.VMSettingsPg)
        self.label_30.setEnabled(False)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_33.addWidget(self.label_30)
        self.txt_vm_p1 = QtWidgets.QLineEdit(self.VMSettingsPg)
        self.txt_vm_p1.setEnabled(False)
        self.txt_vm_p1.setObjectName("txt_vm_p1")
        self.horizontalLayout_33.addWidget(self.txt_vm_p1)
        self.verticalLayout_27.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_31 = QtWidgets.QLabel(self.VMSettingsPg)
        self.label_31.setEnabled(False)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_9.addWidget(self.label_31)
        self.txt_vm_p2 = QtWidgets.QLineEdit(self.VMSettingsPg)
        self.txt_vm_p2.setEnabled(False)
        self.txt_vm_p2.setObjectName("txt_vm_p2")
        self.horizontalLayout_9.addWidget(self.txt_vm_p2)
        self.verticalLayout_27.addLayout(self.horizontalLayout_9)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_27 = QtWidgets.QLabel(self.VMSettingsPg)
        self.label_27.setEnabled(False)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_25.addWidget(self.label_27)
        self.txt_vm_options = QtWidgets.QLineEdit(self.VMSettingsPg)
        self.txt_vm_options.setEnabled(False)
        self.txt_vm_options.setObjectName("txt_vm_options")
        self.verticalLayout_25.addWidget(self.txt_vm_options)
        self.verticalLayout_27.addLayout(self.verticalLayout_25)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem27)
        self.horizontalLayout_35.addLayout(self.verticalLayout_27)
        self.line_8 = QtWidgets.QFrame(self.VMSettingsPg)
        self.line_8.setEnabled(False)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_35.addWidget(self.line_8)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_1_7 = QtWidgets.QLabel(self.VMSettingsPg)
        self.label_1_7.setEnabled(False)
        self.label_1_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_1_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_1_7.setObjectName("label_1_7")
        self.horizontalLayout_31.addWidget(self.label_1_7)
        self.txt_scriptloc = QtWidgets.QLineEdit(self.VMSettingsPg)
        self.txt_scriptloc.setEnabled(False)
        self.txt_scriptloc.setDragEnabled(True)
        self.txt_scriptloc.setClearButtonEnabled(False)
        self.txt_scriptloc.setObjectName("txt_scriptloc")
        self.horizontalLayout_31.addWidget(self.txt_scriptloc)
        self.btn_explore_6_2 = QtWidgets.QPushButton(self.VMSettingsPg)
        self.btn_explore_6_2.setEnabled(False)
        self.btn_explore_6_2.setObjectName("btn_explore_6_2")
        self.horizontalLayout_31.addWidget(self.btn_explore_6_2)
        self.verticalLayout_26.addLayout(self.horizontalLayout_31)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem28)
        self.horizontalLayout_35.addLayout(self.verticalLayout_26)
        self.verticalLayout_28.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_28 = QtWidgets.QLabel(self.VMSettingsPg)
        self.label_28.setEnabled(False)
        self.label_28.setMinimumSize(QtCore.QSize(200, 0))
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_29.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.VMSettingsPg)
        self.label_29.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_29.setFont(font)
        self.label_29.setAutoFillBackground(True)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_29.addWidget(self.label_29)
        self.btn_vmcmd_update = QtWidgets.QPushButton(self.VMSettingsPg)
        self.btn_vmcmd_update.setEnabled(False)
        self.btn_vmcmd_update.setObjectName("btn_vmcmd_update")
        self.horizontalLayout_29.addWidget(self.btn_vmcmd_update)
        self.verticalLayout_28.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.checkBox = QtWidgets.QCheckBox(self.VMSettingsPg)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_28.addWidget(self.checkBox)
        self.txt_filename_in_4 = QtWidgets.QLineEdit(self.VMSettingsPg)
        self.txt_filename_in_4.setEnabled(False)
        self.txt_filename_in_4.setDragEnabled(True)
        self.txt_filename_in_4.setClearButtonEnabled(False)
        self.txt_filename_in_4.setObjectName("txt_filename_in_4")
        self.horizontalLayout_28.addWidget(self.txt_filename_in_4)
        self.btn_explore_6_3 = QtWidgets.QPushButton(self.VMSettingsPg)
        self.btn_explore_6_3.setEnabled(False)
        self.btn_explore_6_3.setObjectName("btn_explore_6_3")
        self.horizontalLayout_28.addWidget(self.btn_explore_6_3)
        self.verticalLayout_28.addLayout(self.horizontalLayout_28)
        tournament_ui.addPage(self.VMSettingsPg)

        self.retranslateUi(tournament_ui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tournament_ui)

    def retranslateUi(self, tournament_ui):
        _translate = QtCore.QCoreApplication.translate
        tournament_ui.setWindowTitle(_translate("tournament_ui", "xXx Tournament xXx"))
        self.FileSelectionPg.setTitle(_translate("tournament_ui", "File Selection"))
        self.FileSelectionPg.setSubTitle(_translate("tournament_ui", "Choose a file for defualts"))
        self.label_1_1.setText(_translate("tournament_ui", "Input setting file"))
        self.btn_explore_1_1.setText(_translate("tournament_ui", "Explore"))
        self.label_1_2.setText(_translate("tournament_ui", "Output setting file"))
        self.btn_explore_1_2.setText(_translate("tournament_ui", "Explore"))
        self.btn_load.setText(_translate("tournament_ui", "Load \n"
" All Settings"))
        self.PlayerSelectionPg.setTitle(_translate("tournament_ui", "Player Selection"))
        self.PlayerSelectionPg.setSubTitle(_translate("tournament_ui", "Choose Players to add/ remove from the tournament"))
        self.label_1_3.setText(_translate("tournament_ui", "Player Source Folder"))
        self.btn_explore_2_1.setText(_translate("tournament_ui", "Explore"))
        self.btn_player_update.setText(_translate("tournament_ui", " Update Players "))
        self.label_25.setText(_translate("tournament_ui", "Select Players"))
        self.label.setText(_translate("tournament_ui", "Not Playing"))
        self.btn_players_select.setText(_translate("tournament_ui", "->"))
        self.btn_players_deselect.setText(_translate("tournament_ui", "<-"))
        self.label_3.setText(_translate("tournament_ui", "Playing"))
        self.TypeSelectionPg.setTitle(_translate("tournament_ui", "Tournament Type"))
        self.TypeSelectionPg.setSubTitle(_translate("tournament_ui", "Choose the type of tournament to be played"))
        self.rbtn_robin.setText(_translate("tournament_ui", "Round Robin"))
        self.rbtn_single.setText(_translate("tournament_ui", "Single Elimination"))
        self.label_8.setText(_translate("tournament_ui", "Not implemented"))
        self.rbtn_swiss.setText(_translate("tournament_ui", "Swiss Style"))
        self.rbtn_multi.setText(_translate("tournament_ui", "Multi Elimination"))
        self.TournamentSettingsPg.setTitle(_translate("tournament_ui", "Tournament Type Settings"))
        self.TournamentSettingsPg.setSubTitle(_translate("tournament_ui", "Tournament settings for the individual types"))
        self.chk_robin_groups.setText(_translate("tournament_ui", "Groups"))
        self.label_robbin_groups.setText(_translate("tournament_ui", "Amount of groups"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.roundrobin_elim_tab), _translate("tournament_ui", "Round Robin"))
        self.chk_single_third.setText(_translate("tournament_ui", "3rd Place"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.single_elim_tab), _translate("tournament_ui", "Single Elimination"))
        self.label_13.setText(_translate("tournament_ui", "Not implemented"))
        self.label_14.setText(_translate("tournament_ui", "Amount"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.multi_elim_tab), _translate("tournament_ui", "Multi - Elimination"))
        self.label_12.setText(_translate("tournament_ui", "Not implemented"))
        self.chk_swiss_pnt.setText(_translate("tournament_ui", "Maxium Points (For Multi Stage)"))
        self.chk_swiss_replay.setText(_translate("tournament_ui", "Alllow Players to Replay each other"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.swiss_tab), _translate("tournament_ui", "Swiss Style"))
        self.GeneralSettingPg.setTitle(_translate("tournament_ui", "General Setting"))
        self.GeneralSettingPg.setSubTitle(_translate("tournament_ui", "Choose and edit setting for the tournament overall "))
        self.label_20.setText(_translate("tournament_ui", "Amount of matches to be played:"))
        self.label_19.setText(_translate("tournament_ui", "Best of: "))
        self.label_22.setText(_translate("tournament_ui", "Points for a:"))
        self.label_23.setText(_translate("tournament_ui", "Win"))
        self.label_24.setText(_translate("tournament_ui", "Draw"))
        self.label_26.setText(_translate("tournament_ui", "Loss"))
        self.label_16.setText(_translate("tournament_ui", "Seeding Type"))
        self.rbtn_set_noseed.setText(_translate("tournament_ui", "No seeding"))
        self.rbtn_set_rdmseed.setText(_translate("tournament_ui", "Random"))
        self.rbtn_set_seeded.setText(_translate("tournament_ui", "Seeded"))
        self.label_6.setText(_translate("tournament_ui", "Show full result \n"
"after end of every:"))
        self.radioButton.setText(_translate("tournament_ui", "Tournament"))
        self.radioButton_2.setText(_translate("tournament_ui", "Round"))
        self.radioButton_3.setText(_translate("tournament_ui", "Match"))
        self.label_15.setText(_translate("tournament_ui", "Not implemented"))
        self.chk_set_watch.setText(_translate("tournament_ui", "Watch each game"))
        self.label_21.setText(_translate("tournament_ui", "Puase time between games"))
        self.label_17.setText(_translate("tournament_ui", "ELO SETTINGS"))
        self.chk_set_elo.setText(_translate("tournament_ui", "Adjust ELO"))
        self.label_1_4.setText(_translate("tournament_ui", "Specific ELO data"))
        self.btn_explore_5_1.setText(_translate("tournament_ui", "Explore"))
        self.label_18.setText(_translate("tournament_ui", "K Value"))
        self.VMSettingsPg.setTitle(_translate("tournament_ui", "VM Settings"))
        self.VMSettingsPg.setSubTitle(_translate("tournament_ui", "Edit player variables and vm options"))
        self.label_33.setText(_translate("tournament_ui", " !! \n"
" NOTHING HERE WORKS YET, \n"
" THIS PROGRAM ONLY WORKS WITH 42 - FILLER \n"
" !!"))
        self.label_32.setText(_translate("tournament_ui", "Not implemented"))
        self.btn_vminfo.setText(_translate("tournament_ui", "Important information about scoring and the script/vm"))
        self.rbtn_vm.setText(_translate("tournament_ui", "Use VM"))
        self.rbtn_script.setText(_translate("tournament_ui", "Use Script"))
        self.label_1_6.setText(_translate("tournament_ui", "Virtal Machine"))
        self.btn_explore_6_1.setText(_translate("tournament_ui", "Explore"))
        self.label_30.setText(_translate("tournament_ui", "Player 1 variable"))
        self.label_31.setText(_translate("tournament_ui", "Player 2 variable"))
        self.label_27.setText(_translate("tournament_ui", "Addition Options"))
        self.label_1_7.setText(_translate("tournament_ui", "Script"))
        self.btn_explore_6_2.setText(_translate("tournament_ui", "Explore"))
        self.label_28.setText(_translate("tournament_ui", "Example of a game excution command:"))
        self.label_29.setText(_translate("tournament_ui", "Example command"))
        self.btn_vmcmd_update.setText(_translate("tournament_ui", "Update"))
        self.checkBox.setText(_translate("tournament_ui", "Visualizer"))
        self.btn_explore_6_3.setText(_translate("tournament_ui", "Explore"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tournament_ui = QtWidgets.QWizard()
    ui = Ui_tournament_ui()
    ui.setupUi(tournament_ui)
    tournament_ui.show()
    sys.exit(app.exec_())

